[package]
name = "sdl2_ttf"
description = "SDL2_ttf bindings for Rust"
repository = "https://github.com/andelf/rust-sdl2_ttf"
version = "0.2.3"
license = "MIT"
readme = "README.md"
authors = ["ShuYu Wang <andelf@gmail.com>"]
keywords = ["SDL", "windowing", "graphics", "font"]

[lib]
name = "sdl2_ttf"
path = "src/sdl2_ttf/lib.rs"

[dependencies]
bitflags = "^0.1"
sdl2 = "^0.4"
sdl2-sys = "^0.4.0"
libc = "^0.1.6"

# [dependencies.sdl2]
# git = "https://github.com/AngryLawyer/rust-sdl2/"

# [dependencies.sdl2-sys]
# git = "https://github.com/AngryLawyer/rust-sdl2/"

[[bin]]
name = "demo"
path = "src/demo/main.rs"
